### ISSUE TITLE
Cannot find scannet.py when preparing scannet data.

### ISSUE THREAD

**Issue by tomsal** [Sekunde/Pri3D#1]
Hi!

first of all, thanks for sharing the code! Great job!

When preparing the scannet data for pretraining, I cannot find the file `scannet.py`. Do you have any idea what went wrong?

This is where the issue occurs: https://github.com/Sekunde/Pri3D/blob/63c728b0a2236529cf24b8095d0d719f4f92451f/README.md#L74
```
cd pretrain/data_preprocess/scannet
python scannet.py --input SCANNET_DATA --output SCANNET_OUT_PATH
```

**Comment by Sekunde** [comment]
Hi, 

Thanks for pointing it out. It were some typos and already fixed.

**Comment by tomsal** [comment]
Thanks!
