### ISSUE TITLE
Model zoo request: VIEW only and GEO only on ScanNet

### ISSUE THREAD

**Issue by tomsal** [Sekunde/Pri3D#2]
I am really interested in how the features change when using the different losses (VIEW only, GEO only, or also combined). From what I've seen, all provided models were trained using the same loss or otherwise on a different dataset. (Or did I overlook something?) Is it possible to make more models available, e.g. VIEW only and GEO only on ScanNet? 

I am aware this is pushing your kindness, because it's already great that you provided such an extensive codebase. Still, I at least wanted to ask. :)

**Comment by Sekunde** [comment]
Hi, 

I added the model zoo requested, please check it out again.

**Comment by tomsal** [comment]
Great! Thank you so much!
