### ISSUE TITLE
Pre-trained Model without downstream task fine-tuning

### ISSUE THREAD

**Issue by jiadingfang** [Sekunde/Pri3D#3]
Hi,

Thanks for the codebase. It seems like the current provided model zoo only have models fine-tuned on different downstream tasks. I somehow want to take a look at the original features just from pre-training without any fine-tuning so that I can maybe use them for other tasks. Do you think such request makes sense, or you think I could use one from the existing model zoo and it should work similarly?

Thanks in advance.

**Comment by Sekunde** [comment]
Hi, 
The naming in model zoos is a bit misleading. 
The pre-trained model means weights from pre-training w/o fine-tuning; the logs and curves are, however, from fine-tuning in different downstream tasks and just released for reference.

**Comment by jiadingfang** [comment]
Thanks for replying! 
Just to clarify, if "the pre-trained model means weights from pre-training w/o fine-tuning", does that mean a few of the provided weights are duplicates? For example, pre-trained model 100% scene scannet resnet50 (View+Geo) in section "Semantic Segmentation on ScanNet" and "Semantic Segmentation on NYUv2". I can almost confirm it is the case because their filenames are only different by a learning_rate number (01 vs 001, although not sure why), but just to make sure.

**Comment by Sekunde** [comment]
yes, there are duplicates, you understand correctly.

**Comment by jiadingfang** [comment]
Thanks for clarifying!
