### ISSUE TITLE
Was "pretrain.depth = True" set in modelzoo?

### ISSUE THREAD

**Issue by tomsal** [Sekunde/Pri3D#4]
In the scannet.sh script, the setting "pretrain.depth" is set to "True":
https://github.com/Sekunde/Pri3D/blob/a607a05c3a3385da1202ee38201de79a161023bb/pretrain/pri3d/scripts/scannet.sh#L26

Was this also the setting that was used for all the models in the modelzoo? If I understand correctly, this enables the depth loss in addition to the VIEW and GEO loss, is that correct?
https://github.com/Sekunde/Pri3D/blob/a607a05c3a3385da1202ee38201de79a161023bb/pretrain/pri3d/model/model.py#L94

**Comment by Sekunde** [comment]
Hi, 

Yes, we turn on this flag to have depth prediction as a proxy loss by default. 
Turning it off might slightly harm the performance, e.g. 61 miou to 60ish in scannet semantic segmentation.

**Comment by tomsal** [comment]
Thanks a lot for the quick answer! The depth loss seems quite a bit more sophisticated, e.g. compared to a L1-loss. Is there some literature where this kind of depth loss is explained?

**Comment by Sekunde** [comment]
Hi, 
in depth prediction, geometric loss is normally used in addition to L1 loss, e.g. from this one https://github.com/JunjH/Revisiting_Single_Depth_Estimation

**Comment by tomsal** [comment]
Great, thanks!
