### ISSUE TITLE
Did you validate the usefulness of the pretrained 3D CNN in 3D tasks?

### ISSUE THREAD

**Issue by sunnyHelen** [Sekunde/Pri3D#5]
Hi, thanks for sharing your great and comprehensive work. 
As my understanding, 3D backbone is also trained during the pretraining process. Did you do any experiment to validate the usefulness of the pretrained 3D network for downstream 3D tasks?

**Comment by Sekunde** [comment]
hi, we validate the 3d part in the early phase of the project, and it didn't help on 3D semantic segmentation; however, we didn't validate the 3d part in the late stage of the project when our pre-trained model is getting better than the one in earlier phase.

Feel free to try our current model out in terms of 3d tasks.

**Comment by sunnyHelen** [comment]
Ok, thanks for your reply.
