### ISSUE TITLE
About computing overlap ratio of two frams

### ISSUE THREAD

**Issue by Dingry** [Sekunde/Pri3D#6]
Thanks for your great work and released code! I notice that in your paper the pixel correspondences between the two frames are then determined as those whose 3D world locations lie within 2cm of each other. But in the preprocess script `pretrain/data_preprocess/scannet/compute_full_overlapping.py`, the match_indices radius is set as voxel_size*1.5, which by default is 7.5cm I think. I am confused with the 2cm and 7.5cm. Could you rovide some explanations? Thanks.

**Comment by Sekunde** [comment]
yes, we use a larger threshold in the preparation of the training data, as we want to have a buffer zone. compute_full_overlapping.py outputs the file list of frame pairs that guarantee the existence of correspondences, and larger threshold can give us more training samples. Eventually, we only sample 1024 correspondences.

**Comment by Dingry** [comment]
Thanks for your reply!
